insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','1');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','1');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','1');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('LOL','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('LOL','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','1');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('LOL','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','5');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('PUBG','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','4');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('PUBG','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('PUBG','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('WAR LOAD','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('WAR LOAD','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','1');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('WAR LOAD','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','5');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('URSA','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','0');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('URSA','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','4');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('URSA','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('URSA','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('WK KINGGG','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','1');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('WK KINGGG','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','1');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('WK KINGGG','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('WK KINGGG','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','4');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Monkey King','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','5');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Monkey King','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','4');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Monkey King','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Monkey King','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Monkey King','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','1');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','1');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','1');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','1');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('LOL','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('LOL','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','1');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('LOL','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','5');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('PUBG','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','4');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('PUBG','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('PUBG','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('WAR LOAD','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('WAR LOAD','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','1');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('WAR LOAD','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','5');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('URSA','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','0');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('URSA','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','4');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('URSA','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('URSA','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('WK KINGGG','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','1');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('WK KINGGG','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('WK KINGGG','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('WK KINGGG','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','4');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Monkey King','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','5');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Monkey King','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','4');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Monkey King','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Monkey King','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Monkey King','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','1');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','1');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','1');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','1');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('LOL','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('LOL','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','1');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('LOL','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','5');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('PUBG','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','4');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('PUBG','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('PUBG','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('WAR LOAD','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('WAR LOAD','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','1');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('WAR LOAD','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','5');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('URSA','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','4');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('URSA','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','4');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('URSA','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('URSA','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('WK KINGGG','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','1');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('WK KINGGG','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('WK KINGGG','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('WK KINGGG','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','4');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Monkey King','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','5');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Monkey King','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','4');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Monkey King','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Monkey King','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Monkey King','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','1');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','1');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','1');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','1');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('LOL','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('LOL','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','1');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('LOL','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','5');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('PUBG','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','4');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('PUBG','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('PUBG','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('WAR LOAD','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('WAR LOAD','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','1');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('WAR LOAD','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','5');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('URSA','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','0');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('URSA','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','4');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('URSA','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('URSA','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('WK KINGGG','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','1');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('WK KINGGG','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('WK KINGGG','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('WK KINGGG','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','4');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Monkey King','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','5');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Monkey King','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','4');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Monkey King','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Monkey King','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Monkey King','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','1');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','1');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','1');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','1');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','5');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('LOL','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('LOL','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','1');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('LOL','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','5');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('PUBG','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','4');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('PUBG','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('PUBG','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('WAR LOAD','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('WAR LOAD','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','1');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('WAR LOAD','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','5');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('URSA','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('URSA','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','4');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('URSA','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('URSA','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('WK KINGGG','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','1');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('WK KINGGG','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','1');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('WK KINGGG','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('WK KINGGG','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','4');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Monkey King','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','5');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Monkey King','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','4');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Monkey King','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Monkey King','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Monkey King','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','1');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','1');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','1');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','1');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Dota2','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('LOL','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('LOL','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','1');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('LOL','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','5');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('PUBG','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','4');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('PUBG','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('PUBG','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('WAR LOAD','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('WAR LOAD','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','1');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('WAR LOAD','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','5');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('URSA','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('URSA','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','4');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('URSA','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('URSA','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('WK KINGGG','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','1');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('WK KINGGG','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','4');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('WK KINGGG','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('WK KINGGG','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','4');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Monkey King','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','5');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Monkey King','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','4');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Monkey King','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','3');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Monkey King','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','2');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Monkey King','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','1');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Monkey King','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','7');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Monkey King','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','7');
insert into tb_article (title,description,author,thumbnail,created_date,category_id) values ('Monkey King','FUN GAME','LAUGHING','0.jpg','Thu Jun 13 23:59:24 ICT 2019','7');




insert into tb_category (category_id, category_name) values ('1','Something cannot say');
insert into tb_category (category_id, category_name) values ('2','Spring');
insert into tb_category (category_id, category_name) values ('3','Game');
insert into tb_category (category_id, category_name) values ('4','Youtube');
insert into tb_category (category_id, category_name) values ('5','Sabay');
insert into tb_category (category_id, category_name) values ('6','Dota');
insert into tb_category (category_id, category_name) values ('7','Dota2');